version: "3.8"
services:
  web:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - web_data:/usr/src/app/static
    environment:
      FLASK_ENV: development
    depends_on:
    - postgres

  postgres:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/
volumes:
    web_data:
    db_data:
